// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using NeighborhoodWatch;
//
//    var otherTeamPageModel = OtherTeamPageModel.FromJson(jsonString);

namespace NeighborhoodWatch
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class OtherTeamPageModel
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }
    }

    public partial class OtherTeamPageModel
    {
        public static List<OtherTeamPageModel> FromJson(string json) => JsonConvert.DeserializeObject<List<OtherTeamPageModel>>(json, NeighborhoodWatch.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<OtherTeamPageModel> self) => JsonConvert.SerializeObject(self, NeighborhoodWatch.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
