// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Neighborhood_Watch.ApiData;
//
//    var stateDataModel = StateDataModel.FromJson(jsonString);

namespace Neighborhood_Watch.ApiData
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class StateDataModel
    {
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Code")]
        public string Code { get; set; }
    }

    public partial class StateDataModel
    {
        public static List<StateDataModel> FromJson(string json) => JsonConvert.DeserializeObject<List<StateDataModel>>(json, Neighborhood_Watch.ApiData.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<StateDataModel> self) => JsonConvert.SerializeObject(self, Neighborhood_Watch.ApiData.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
